In [43]:
import pandas as pd

# Import the excel file and call it xls_file
xls_file = pd.ExcelFile('Updated_Data_Pie.xls')
xls_file
# View the excel file's sheet names
xls_file.sheet_names

df = xls_file.parse('Worksheet')


df

,Education,Year2009,Year2010,Year2011,Year2012,Year2013,Year2014,Year2015,Total
0,Upto 8th Standard,18,5,8,11,24,0,37,103
1,9th and 10 standard,0,4,0,0,0,305,0,309
2,Above standard 10,23,2,16,18,21,0,5,85
3,Qualification Unnown,22,24,15,13,26,0,12,112
4,Upto 8th Standard,38,58,5,18,26,22,72,239
5,9th and 10 standard,0,0,0,0,0,0,0,0
6,Above standard 10,131,113,103,114,81,82,90,714
7,Qualification Unnown,102,114,126,104,93,114,96,749
8,Upto 8th Standard,9275,5220,10465,6425,13410,6014,4903,55712
9,9th and 10 standard,14617,23490,0,19298,0,0,0,57405
10,Above standard 10,9826,7849,20150,8144,12902,10485,13022,82378
11,Qualification Unnown,9882,8040,13550,8657,17170,7941,6333,71573
12,Above standard 10,96,89,86,87,84,83,88,613
13,Qualification Unnown,107,90,113,76,131,61,104,682
14,Upto 8th Standard,103,104,57,88,93,61,92,598
15,9th and 10 standard,0,10,7,0,0,0,0,17
16,Upto 8th Standard,1095,0,0,0,2582,1968,2221,7866
17,9th and 10 standard,0,5828,6569,6535,0,0,0,18932
18,Above standard 10,2070,0,0,0,2075,2629,2240,9014
19,Qualification Unnown,1704,0,0,0,2554,2547,2498,9303
20,Upto 8th Standard,4345,2749,2727,2660,2702,2087,2634,19904
21,9th and 10 standard,0,0,0,0,0,0,0,0
22,Above standard 10,2447,3084,3810,3722,3737,3826,3940,24566
23,Qualification Unnown,3273,5200,4136,3938,3761,3643,2981,26932
24,Upto 8th Standard,0,46,5,112,79,0,0,242
25,9th and 10 standard,424,174,66,58,0,369,416,1507
26,Above standard 10,0,168,358,210,218,0,0,954
27,Qualification Unnown,0,68,8,39,113,0,0,228
28,Upto 8th Standard,3266,3101,2977,2888,2926,4152,2626,21936
29,9th and 10 standard,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
114,Above standard 10,7452,7605,6792,5475,5246,7516,7829,47915
115,Qualification Unnown,8758,7966,7761,5895,5500,8483,8238,52601
116,Upto 8th Standard,164,50,103,6,53,39,70,485
117,9th and 10 standard,0,21,0,0,0,0,0,21
118,Above standard 10,215,49,166,8,64,63,51,616
119,Qualification Unnown,185,66,137,144,127,101,98,858
120,Upto 8th Standard,10160,11684,11481,8424,8690,9089,10151,69679
121,Above standard 10,29260,29890,32655,29871,35767,38094,36603,232140
122,Qualification Unnown,21374,23422,21737,18826,21781,20067,22305,149512
123,9th and 10 standard,0,0,0,10636,0,0,0,10636
124,9th and 10 standard,0,0,0,0,0,0,0,0
125,Above standard 10,0,0,0,0,0,5702,10359,16061
126,Qualification Unnown,0,0,0,0,0,7098,5670,12768
127,Upto 8th Standard,0,0,0,0,0,7278,5223,12501
128,Upto 8th Standard,98,397,122,290,297,260,237,1701
129,9th and 10 standard,0,0,0,0,0,0,0,0
130,Above standard 10,286,205,379,222,176,169,140,1577
131,Qualification Unnown,481,299,333,376,345,287,270,2391
132,Upto 8th Standard,7669,7494,8223,8520,9208,10876,7086,59076
133,9th and 10 standard,0,0,190,0,0,0,0,190
134,Above standard 10,10361,10895,10782,10995,11238,13684,17191,85146
135,Qualification Unnown,10125,9973,10090,10457,10169,6474,8108,65396
136,Upto 8th Standard,258,420,323,318,223,569,601,2712
137,9th and 10 standard,0,0,0,393,0,0,0,393
138,Above standard 10,734,263,713,456,566,276,410,3418
139,Qualification Unnown,409,810,472,305,508,565,512,3581
140,Upto 8th Standard,5167,408,967,1494,823,4807,4827,18493
141,9th and 10 standard,0,13064,11719,8511,8964,0,0,42258
142,Above standard 10,718,494,841,974,1287,2368,3674,10356
143,Qualification Unnown,5249,922,1418,1311,1340,5700,4707,20647

In [44]:
import plotly.plotly as py
import plotly.graph_objs as go
import pandas as pd

xls_file = pd.ExcelFile('Updated_Data.xls')
xls_file
# View the excel file's sheet names
xls_file.sheet_names

ds = xls_file.parse('Worksheet')


labels = df.States
values = df.Total
colors = ['#FEBFB3', '#E1396C', '#96D38C', '#D0F9B1']

trace = go.Pie(labels=labels, values=values,
               hoverinfo='label+percent', textinfo='value', 
               textfont=dict(size=20),
               marker=dict(colors=colors, 
                           line=dict(color='#000000', width=2)))

py.iplot([trace], filename='donut')

In [52]:
import plotly.plotly as py
import plotly.graph_objs as go

xls_file = pd.ExcelFile('Updated_Data_Pie.xls')
xls_file
# View the excel file's sheet names
xls_file.sheet_names

df = xls_file.parse('Worksheet')
fig = {
  "data": [
    {
      "values": df.Total ,
      "labels":df.Education,
      'marker': {'colors': ['rgb(146, 123, 21)',
                                  'rgb(177, 180, 34)',
                                  'rgb(206, 206, 40)',
                                  'rgb(175, 51, 21)',
                                  'rgb(35, 36, 21)']},
      "domain": {"x": [.20, 1]},
      "name": "Accident",
      "hoverinfo":"label+percent+name",
      "hole": .4,
      "type": "pie"
    },     
    ],
  "layout": {
        "title":"Accident Count By Education Type",
        "annotations": [
            {
                "font": {
                    "size": 20
                },
                "showarrow": False,
                "text": "States",
                "x": 0.60,
                "y": 0.5
            },
            
        ]
    }
}
py.iplot(fig, filename='pie_chart_subplots')

In [42]:
import plotly.plotly as py
import plotly.graph_objs as go

import numpy as np

N = 500

trace0 = go.Scatter(
    x = df.States,
    y = df.Total,
    name = 'Above',
    mode = 'markers',
    marker = dict(
        size = 10,
        color = 'rgba(152, 0, 0, .8)',
        line = dict(
            width = 2,
            color = 'rgb(0, 0, 0)'
        )
    )
)



data = [trace0]

layout = dict(title = 'Styled Scatter',
              yaxis = dict(zeroline = False),
              xaxis = dict(zeroline = False)
             )

fig = dict(data=data, layout=layout)
py.iplot(fig, filename='styled-scatter')