In [11]:
import matplotlib.pyplot as plt
from matplotlib import cm
import pandas as pd
#import cufflinks as cf
import seaborn as sns
import numpy as np
import random
sns.set_style('white')

%matplotlib inline

In [27]:
# Load raw data into DataFrame using pandas
vehicle_type_df_raw = pd.read_csv('Type_of_Vehicles_and_Type_of_Licence.csv', delimiter=',')
vehicle_type_df_raw[:2]

,SNo,States,OwnerofPrivateVehicle-Accident-2014,OwnerofPrivateVehicle-Killed-2014,OwnerofPublicCommVehicle-Accident-2014,OwnerofPublicCommVehicle-Killed-2014,PaidDriver-Accident-2014,PaidDriver-Killed-2014,Others-Accident-2014,Others-Killed-2014,RegularLicence-Accident-2014,RegularLicence-Killed-2014,LearnersLicence-Accident-2014,LearnersLicence-Killed-2014,WithoutLicence-Accident-2014,WithoutLicence-Killed-2014
0,1,Andhra Pradesh,7051.0,2133.0,3235.0,1128.0,7243.0,2316.0,6911.0,1488.0,21605.0,6194.0,589.0,152.0,2246.0,719.0
1,2,Arunachal Pradesh,53.0,19.0,50.0,12.0,56.0,8.0,46.0,7.0,84.0,24.0,66.0,17.0,55.0,5.0

In [26]:
#replace NaN with 0
vehicle_type_df = vehicle_type_df_raw[~(vehicle_type_df_raw['SNo'] == 'Total')].fillna(0)
vehicle_type_total_df = vehicle_type_df_raw[vehicle_type_df_raw['SNo'] == 'Total']

#validation
vehicle_type_df.head()

,SNo,States,OwnerofPrivateVehicle-Accident-2014,OwnerofPrivateVehicle-Killed-2014,OwnerofPublicCommVehicle-Accident-2014,OwnerofPublicCommVehicle-Killed-2014,PaidDriver-Accident-2014,PaidDriver-Killed-2014,Others-Accident-2014,Others-Killed-2014,RegularLicence-Accident-2014,RegularLicence-Killed-2014,LearnersLicence-Accident-2014,LearnersLicence-Killed-2014,WithoutLicence-Accident-2014,WithoutLicence-Killed-2014
0,1,Andhra Pradesh,7051.0,2133.0,3235.0,1128.0,7243.0,2316.0,6911.0,1488.0,21605.0,6194.0,589.0,152.0,2246.0,719.0
1,2,Arunachal Pradesh,53.0,19.0,50.0,12.0,56.0,8.0,46.0,7.0,84.0,24.0,66.0,17.0,55.0,5.0
2,3,Assam,3525.0,342.0,2264.0,107.0,798.0,28.0,557.0,12.0,7105.0,474.0,28.0,11.0,11.0,4.0
3,4,Bihar,2855.0,829.0,2109.0,261.0,3386.0,188.0,1206.0,159.0,4985.0,758.0,3117.0,450.0,1454.0,229.0
4,5,Chhattisgarh,5823.0,636.0,2809.0,321.0,3192.0,341.0,1997.0,247.0,10202.0,1503.0,2284.0,37.0,1335.0,5.0

In [38]:
# Final
#ToDo : tooltip issue
#Stacked bar plot with bokeh

from bokeh.plotting import figure, show, output_file, ColumnDataSource
from bokeh.palettes import Spectral6
from bokeh.core.properties import value
from math import pi
from bokeh.models import HoverTool

sorted_license_df = vehicle_type_df.sort_values(['RegularLicence-Accident-2014'], ascending=[False])
sorted_license_top20_df = sorted_license_df[:20]

states = list(sorted_license_top20_df['States'])
regular = list(sorted_license_top20_df['RegularLicence-Accident-2014'])
learner = list(sorted_license_top20_df['LearnersLicence-Accident-2014'])
without = list(sorted_license_top20_df['WithoutLicence-Accident-2014'])
print(states)

license_type = ['Regular', 'Learner', 'NoLicense']
colors = ['#2b83ba', '#abdda4', '#ffffbf']

data = {'States' : states,
        'Regular'   : regular,
        'Learner'   : learner,
        'NoLicense'   : without}

source = ColumnDataSource(data=data)

hover = HoverTool(tooltips=[
    ('Regular', '@Regular'),
    ('Learner', '@Learner'),
    ('No License', '@NoLicense')
])


p = figure(x_range=states, plot_height=600, plot_width=800, title="License Types of Driver vs Accidents",
           toolbar_location=None, tools=[hover],
           x_axis_label="States", y_axis_label="No of Accidents")

p.vbar_stack(license_type, x='States', width=0.9, color=colors, source=source,
             legend=[value(x) for x in license_type])

p.xaxis.major_label_orientation = "vertical"
p.xaxis.axis_line_color = "blue"
p.xaxis.axis_label_text_color = "blue"
p.yaxis.axis_label_text_color = "blue"
p.title.align = "center"
p.legend.location = "top_right"
p.legend.orientation = "horizontal"
p.y_range.start = 0.1
p.x_range.range_padding = 0.1
p.axis.minor_tick_in = -3
p.axis.minor_tick_out = 6

show(p)

['Tamil Nadu', 'Maharashtra', 'Madhya Pradesh', 'Karnataka', 'Kerala', 'Rajasthan', 'Andhra Pradesh', 'Gujarat', 'Uttar Pradesh', 'Telangana', 'Chhattisgarh', 'Haryana', 'Orissa', 'Assam', 'West Bengal', 'Bihar', 'Punjab', 'Jharkhand', 'Goa', 'Jammu & Kashmir']

In [39]:
# Final
#ToDo : tooltip issue
#Grouped bar plot with bokeh

from bokeh.plotting import figure, show, output_file, ColumnDataSource
from bokeh.palettes import Spectral6
from bokeh.core.properties import value
from math import pi
from bokeh.models import HoverTool

sorted_license_df = vehicle_type_df.sort_values(['OwnerofPrivateVehicle-Accident-2014'], ascending=[False])
sorted_license_top20_df = sorted_license_df[:20]

states = list(sorted_license_top20_df['States'])
owner_private = list(sorted_license_top20_df['OwnerofPrivateVehicle-Accident-2014'])
owner_public = list(sorted_license_top20_df['OwnerofPublicCommVehicle-Accident-2014'])
paid = list(sorted_license_top20_df['PaidDriver-Accident-2014'])
other = list(sorted_license_top20_df['Others-Accident-2014'])
print(states)

license_type = ['PrivateVehicleOwner', 'PublicVehicleOwner', 'PaidDriver', 'Others']
colors = ['#2b83ba', '#abdda4', '#ffffbf', '#fdae61']

data = {'States' : states,
        'PrivateVehicleOwner'   : owner_private,
        'PublicVehicleOwner'   : owner_public,
        'PaidDriver'   : paid,
        'Others'   : other}

source = ColumnDataSource(data=data)

hover = HoverTool(tooltips=[
    ('Private Owner', '@PrivateVehicleOwner'),
    ('Public', '@PublicVehicleOwner'),
    ('Paid Driver', '@PaidDriver'),
    ('Others', '@Others')
])


p = figure(x_range=states, plot_height=600, plot_width=800, title="Driver Type vs Accidents",
           toolbar_location=None, tools=[hover],
           x_axis_label="States", y_axis_label="No of Accidents")

p.vbar_stack(license_type, x='States', width=0.9, color=colors, source=source,
             legend=[value(x) for x in license_type])

p.xaxis.major_label_orientation = "vertical"
p.xaxis.axis_line_color = "blue"
p.xaxis.axis_label_text_color = "blue"
p.yaxis.axis_label_text_color = "blue"
p.title.align = "center"
p.legend.location = "top_right"
#p.legend.orientation = "horizontal"
p.y_range.start = 0.1
p.x_range.range_padding = 0.1
p.axis.minor_tick_in = -3
p.axis.minor_tick_out = 6

show(p)

['Maharashtra', 'Madhya Pradesh', 'Tamil Nadu', 'Karnataka', 'Kerala', 'Gujarat', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Uttar Pradesh', 'Chhattisgarh', 'West Bengal', 'Assam', 'Bihar', 'Punjab', 'Orissa', 'Goa', 'Jammu & Kashmir', 'Haryana', 'Himachal Pradesh']